version: 0.2

phases:

  pre_build:
    commands:
      - echo Logging in to Amazon ECR
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 317429618990.dkr.ecr.us-east-1.amazonaws.com/thingsboard

  build:
    commands:
      - docker pull thingsboard/tb-postgres
      - docker tag thingsboard/tb-postgres:latest YOUR_ECR_URI:latest

  post_build:
    commands:
      - docker push 317429618990.dkr.ecr.us-east-1.amazonaws.com/thingsboard:latest
